### ISSUE TITLE
[SPEC] Presigning and Signing

### ISSUE THREAD

**Issue by akileshtangella** [webb-tools/cggmp-threshold-ecdsa#10]
# Presigning and Signing SPEC

## Ring-Pedersen Parameters
Unlike in the key refresh presented in the CGGMP '21 paper, FS-DKR does not result in each party having ring-Pedersen parameters. So this is something we have to append to our protocol.

It makes sense to append this to FS-DKR itself.  We also need a ZK that the parameters are generated properly:

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/7463414/197911150-319a3f7d-6d42-472c-bb1a-63eea99935a7.png">

## Presigning and Signing SPECs
The steps for pre-signing and signing are specified clearly in the CGGMP '21 paper. 

<img width="584" alt="image" src="https://user-images.githubusercontent.com/7463414/197910266-4c207496-9376-48ee-b5b9-d2941617063d.png">

<img width="551" alt="image" src="https://user-images.githubusercontent.com/7463414/197910329-d8835fe6-f408-4d37-83f2-b12b8c767996.png">

## What is missing from these SPECs
What is missing from these screenshots is how actually to implement the non-interactive zero-knowledge proofs (NIZKs), but this is also given in the paper. So we provide more screenshots.

In pre-signing round 1, we need:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/7463414/197912171-9d31534f-60cc-4a3e-89ed-c1a83f36888c.png">

In pre-signing rounds 2 and 3 we additionally need:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/7463414/197912253-80dd02aa-4674-47aa-9109-01e0cd9f2931.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/7463414/197912352-1f0a1421-2e2a-402e-b5fa-154695a04f94.png">

In pre-signing round 4, we additionally need:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/7463414/197912510-2a53a709-7198-4d39-a3aa-29622729072f.png">

In signing, we additionally need:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/7463414/197912640-0f3d519d-24e3-4107-a3e9-8224b4f87d8e.png">

## How to make these zero-knowledge proofs non-interactive:
All of the ZKs screenshotted above are three-move protocols. That is, they are interactive. We need to make them non-interactive.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/7463414/197914131-b35dabbf-4952-4815-be46-6ad013f08559.png">

## ZKP Checklist
- [x] Implement ring-Pedersen parameter generation and ZKP
- [ ] Implement Paillier Encryption in Range ZKP (`enc`)
- [ ] Implement Paillier Affine Operation with Group Commitment ZKP (`aff-g`)
- [ ] Implement Knowledge of Exponent Assumption vs. Paillier Encryption ZKP (`log*`)
- [ ] Implement Paillier Multiplication ZKP (`mul`)
- [ ] Implement Paillier Decryption modulo q ZKP (`dec`)
- [ ] Implement Multiplication Paillier vs Group ZKP (`mul*`)

**Comment by drewstone** [comment]
If we are going to need ring pedersen parameters, then we should replace those with the current PDL parameters we're using. AFAIK they are quite similar. Also, we may be able to swap the Ring-pedersen proof with the PDL proof too, unless those params are strictly used as is throughout the protocol.
